# Generated by Django 5.0.1 on 2025-01-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0002_alter_medecin_years_of_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDossier', models.CharField(max_length=50, unique=True)),
                ('identite_du_patient', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('antecedentPersonnel', models.TextField(blank=True, null=True)),
                ('carcinomeFamiliale', models.BooleanField(default=False)),
                ('antecedentFamiliaux', models.TextField(blank=True, null=True)),
                ('ageDecouverte', models.PositiveIntegerField(blank=True, null=True)),
                ('typeHisto', models.CharField(blank=True, choices=[('Papillaire', 'Papillaire'), ('Vesiculaire', 'Vesiculaire'), ('PapilloVesiculaire', 'PapilloVesiculaire'), ('Medullaire', 'Medullaire'), ('Anaplasique', 'Anaplasique'), ('Autres', 'Autres')], max_length=255, null=True)),
                ('clasT', models.CharField(blank=True, choices=[('Mx', 'Mx'), ('M0', 'M0'), ('T1a', 'T1a'), ('T1b', 'T1b'), ('T2', 'T2'), ('T3a', 'T3a'), ('T3b', 'T3b'), ('T4a', 'T4a'), ('T4b', 'T4b')], max_length=50, null=True)),
                ('clasN', models.CharField(blank=True, choices=[('Nx', 'Nx'), ('N0', 'N0'), ('N1a', 'N1a'), ('N1b', 'N1b')], max_length=50, null=True)),
                ('clasM', models.CharField(blank=True, choices=[('Mx', 'Mx'), ('M0', 'M0'), ('M1', 'M1')], max_length=50, null=True)),
                ('focalite', models.CharField(blank=True, choices=[('Uni', 'Unifocale'), ('Bi', 'Bifocale'), ('Multi', 'Multifocale')], max_length=50, null=True)),
                ('stade', models.CharField(blank=True, choices=[('I', 'Stade I'), ('II', 'Stade II'), ('III', 'Stade III'), ('IVA', 'Stade IVA'), ('IVB', 'Stade IVB')], max_length=50, null=True)),
                ('risque', models.CharField(blank=True, choices=[('Faible', 'Faible'), ('Intermediaire', 'Intermédiaire'), ('Haut', 'Haut')], max_length=50, null=True)),
                ('metastase', models.JSONField(blank=True, help_text='Liste des métastases (sélection multiple)', null=True)),
                ('curage', models.JSONField(blank=True, help_text='Liste des curages (sélection multiple)', null=True)),
                ('circonstance', models.JSONField(blank=True, help_text='Liste des circonstances de découverte (sélection multiple)', null=True)),
                ('cures', models.JSONField(blank=True, help_text='Liste des 10 cures', null=True)),
                ('defrenations', models.JSONField(blank=True, help_text='Liste des 3 défrenations', null=True)),
                ('bilans', models.JSONField(blank=True, help_text='Liste des 5 bilans', null=True)),
                ('examens', models.JSONField(blank=True, help_text='Liste des 10 examens', null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('consigne', models.TextField(blank=True, null=True)),
                ('refrac', models.TextField(blank=True, null=True)),
                ('dateRdv', models.DateTimeField(verbose_name='Date et heure du prochain bilan')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
            ],
        ),
    ]
