# Generated by Django 5.0.1 on 2025-03-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDossier', models.CharField(max_length=50, unique=True)),
                ('antecedentPersonnel', models.TextField(blank=True, null=True)),
                ('carcinomeFamiliale', models.BooleanField(default=False)),
                ('antecedentFamiliaux', models.TextField(blank=True, null=True)),
                ('ageDecouverte', models.PositiveIntegerField(blank=True, null=True)),
                ('effraCapsulaire', models.BooleanField(default=False)),
                ('embonVasculaire', models.BooleanField(default=False)),
                ('nbrCure', models.IntegerField(default=0, null=True)),
                ('activiteCumule', models.IntegerField(default=0, null=True)),
                ('thera', models.TextField(default='', max_length=255, null=True)),
                ('typeHisto', models.CharField(blank=True, choices=[('Papillaire', 'Papillaire'), ('Vesiculaire', 'Vesiculaire'), ('PapilloVesiculaire', 'PapilloVesiculaire'), ('Medullaire', 'Medullaire'), ('Anaplasique', 'Anaplasique'), ('Autres', 'Autres')], max_length=255, null=True)),
                ('clasT', models.CharField(blank=True, choices=[('Tx', 'Tx'), ('T0', 'T0'), ('T1a', 'T1a'), ('T1b', 'T1b'), ('T2', 'T2'), ('T3a', 'T3a'), ('T3b', 'T3b'), ('T4a', 'T4a'), ('T4b', 'T4b')], max_length=50, null=True)),
                ('clasN', models.CharField(blank=True, choices=[('Nx', 'Nx'), ('N0', 'N0'), ('N1a', 'N1a'), ('N1b', 'N1b')], max_length=50, null=True)),
                ('clasM', models.CharField(blank=True, choices=[('Mx', 'Mx'), ('M0', 'M0'), ('M1', 'M1')], max_length=50, null=True)),
                ('focalite', models.CharField(blank=True, choices=[('Uni', 'Unifocale'), ('Bi', 'Bifocale'), ('Multi', 'Multifocale')], max_length=50, null=True)),
                ('stade', models.CharField(blank=True, choices=[('I', 'Stade I'), ('II', 'Stade II'), ('III', 'Stade III'), ('IVA', 'Stade IVA'), ('IVB', 'Stade IVB')], max_length=50, null=True)),
                ('risque', models.CharField(blank=True, choices=[('Faible', 'Faible'), ('Intermediaire', 'Intermédiaire'), ('Haut', 'Haut')], max_length=50, null=True)),
                ('metastase', models.JSONField(blank=True, help_text='Liste des métastases (sélection multiple)', null=True)),
                ('curage', models.JSONField(blank=True, help_text='Liste des curages (sélection multiple)', null=True)),
                ('circonstance', models.JSONField(blank=True, help_text='Liste des circonstances de découverte (sélection multiple)', null=True)),
                ('cure1', models.TextField(blank=True, default='', null=True)),
                ('cure2', models.TextField(blank=True, default='', null=True)),
                ('cure3', models.TextField(blank=True, default='', null=True)),
                ('cure4', models.TextField(blank=True, default='', null=True)),
                ('cure5', models.TextField(blank=True, default='', null=True)),
                ('cure6', models.TextField(blank=True, default='', null=True)),
                ('cure7', models.TextField(blank=True, default='', null=True)),
                ('cure8', models.TextField(blank=True, default='', null=True)),
                ('cure9', models.TextField(blank=True, default='', null=True)),
                ('cure10', models.TextField(blank=True, default='', null=True)),
                ('bilan1', models.TextField(blank=True, default='', null=True)),
                ('bilan2', models.TextField(blank=True, default='', null=True)),
                ('bilan3', models.TextField(blank=True, default='', null=True)),
                ('bilan4', models.TextField(blank=True, default='', null=True)),
                ('bilan5', models.TextField(blank=True, default='', null=True)),
                ('bilan6', models.TextField(blank=True, default='', null=True)),
                ('bilan7', models.TextField(blank=True, default='', null=True)),
                ('bilan8', models.TextField(blank=True, default='', null=True)),
                ('bilan9', models.TextField(blank=True, default='', null=True)),
                ('bilan10', models.TextField(blank=True, default='', null=True)),
                ('examen1', models.TextField(blank=True, default='', null=True)),
                ('examen2', models.TextField(blank=True, default='', null=True)),
                ('examen3', models.TextField(blank=True, default='', null=True)),
                ('examen4', models.TextField(blank=True, default='', null=True)),
                ('examen5', models.TextField(blank=True, default='', null=True)),
                ('examen6', models.TextField(blank=True, default='', null=True)),
                ('examen7', models.TextField(blank=True, default='', null=True)),
                ('examen8', models.TextField(blank=True, default='', null=True)),
                ('examen9', models.TextField(blank=True, default='', null=True)),
                ('examen10', models.TextField(blank=True, default='', null=True)),
                ('defrenations1', models.TextField(blank=True, default='', null=True)),
                ('defrenations2', models.TextField(blank=True, default='', null=True)),
                ('defrenations3', models.TextField(blank=True, default='', null=True)),
                ('defrenations4', models.TextField(blank=True, default='', null=True)),
                ('defrenations5', models.TextField(blank=True, default='', null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('consigne', models.TextField(blank=True, null=True)),
                ('refrac', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dossierMedical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRdv', models.DateTimeField(verbose_name='Date et heure du prochain bilan')),
                ('motif', models.TextField(blank=True, default='', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='dossierMedical.patient')),
            ],
        ),
    ]
