# Generated by Django 5.0.1 on 2025-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='risque',
            field=models.CharField(blank=True, choices=[('Faible', 'Faible'), ('Intermediaire', 'Intermediaire'), ('Haut', 'Haut')], max_length=50, null=True),
        ),
    ]
