# Generated by Django 5.0.1 on 2025-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='annee_naissance',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
