# Generated by Django 5.0.1 on 2025-01-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0002_dossiermedical_annee_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='annee_naissance',
        ),
    ]
