# Generated by Django 5.0.1 on 2025-01-08 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0004_alter_dossiermedical_medecin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='identite_du_patient',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='telephone',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dossierMedical.patient'),
        ),
    ]
