# Generated by Django 5.0.1 on 2025-01-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0005_remove_dossiermedical_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='activiteCumule',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='effraCapsulaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='embonVasculaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='nbrCure',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='thera',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='clasT',
            field=models.CharField(blank=True, choices=[('Tx', 'Tx'), ('T0', 'T0'), ('T1a', 'T1a'), ('T1b', 'T1b'), ('T2', 'T2'), ('T3a', 'T3a'), ('T3b', 'T3b'), ('T4a', 'T4a'), ('T4b', 'T4b')], max_length=50, null=True),
        ),
    ]
