# Generated by Django 5.0.1 on 2025-01-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0006_dossiermedical_activitecumule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='bilans',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='cures',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='defrenations',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='examens',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='bilan9',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cure9',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='defrenations1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='defrenations2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='defrenations3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='defrenations4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='defrenations5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='examen9',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
