# Generated by Django 5.0.1 on 2025-01-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0007_remove_dossiermedical_bilans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='dateRdv',
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRdv', models.DateTimeField(verbose_name='Date et heure du prochain bilan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='dossierMedical.patient')),
            ],
        ),
    ]
