# Generated by Django 5.0.1 on 2025-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierMedical', '0008_remove_dossiermedical_daterdv_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='motif',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
