# Generated by Django 5.0.1 on 2025-03-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'institution")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('institution_type', models.CharField(max_length=100, verbose_name="Type d'institution")),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
