# Generated by Django 5.0.1 on 2025-04-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='name',
        ),
    ]
