# Generated by Django 5.0.1 on 2024-12-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience"),
        ),
    ]
