# Generated by Django 5.0.1 on 2025-03-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='institution',
        ),
    ]
