# Generated by Django 5.0.1 on 2025-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_remove_medecin_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
