# Generated by Django 5.0.1 on 2025-01-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_alter_medecin_years_of_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=255)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
            ],
        ),
    ]
