# Generated by Django 5.0.1 on 2025-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0004_medecin_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
