# Generated by Django 5.0.1 on 2025-01-24 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0005_medecin_bio_alter_medecin_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='photo',
        ),
        migrations.CreateModel(
            name='PhotoProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
