# Generated by Django 5.0.1 on 2025-03-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name="Spécialité d'assistance")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Statut actif')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='medecin.medecin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
