# Generated by Django 5.0.1 on 2025-03-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='medecin',
        ),
    ]
