# Generated by Django 5.0.1 on 2025-04-02 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_remove_assistant_medecin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
